apiVersion: v1
kind: Secret
metadata:
  name: daksh-secret
  namespace: daksh-in
type: Opaque
stringData:
  SUPABASE_URL: "https://kcgnducotksodfmmaxck.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY: ""
  PORT: "3000"
  RESEND_API_KEY: "re_LaptTfeB_Fb1o1DXVKwjVSvZ3S63cnHmn"
